### ISSUE TITLE
Guaranteed analysis title

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-pipeline#27]
As requested, we need to add a new field in the schema to describe the title of the guaranteed analysis.

![image](https://github.com/user-attachments/assets/7fdf5722-c711-4295-a90d-017e68cc0ae5)

Verbatim quote: "Le titre est important puisque selon que "minimal" apparaît ou pas, les termes utilisés pour les éléments nutritifs vont changés aussi."

**Comment by Francois-Werbrouck** [comment]
As discussed, it would also be beneficial to extract a boolean stating if the title refers to the minimal analysis (x=>) or if it only is an analysis (x~=)

**Comment by snakedye** [comment]
I didn't read the verbatim quote. If it's only checking that the word "minimal" appears in the title it should be here.
