### ISSUE TITLE
As a dev, I want the pipeline to determine if the guaranteed analysis is minimal or not

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-pipeline#35]
## Description

We are currently able to extract the guaranteed analysis title from the data, but we don't have a way to assess whether the guaranteed analysis is minimal. This issue is to explore ways to get that information within the pipeline.

**Acceptance Criteria**

- Implement logic to determine whether a guaranteed analysis is minimal.
- Ensure this logic can be integrated with the current system that extracts the guaranteed analysis title.
- Assess the impact of performance, both from the accuracy and speed points of view.
- Update the analysis data format accordingly.

**Additional Information**

**Comment by snakedye** [comment]
From what I just heard from @SamuelPelletierEvraire, we can't really know if it's minimal or not.

**Comment by k-allagbe** [comment]
> From what I just heard from @SamuelPelletierEvraire, we can't really know if it's minimal or not.

Please elaborate.

**Comment by snakedye** [comment]
There's not a specific keyword in the title that would let us know. The minimal guaranteed analysis usually contains less information than the regular but there's no set length. One minimal for one fertilizer could be bigger than a regular on another. I'll try to share the meeting where I had this discussion.
