### ISSUE TITLE
As a Dev, I want a valid package from current project to use in calling repositories

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/fertiscan-pipeline#57]
Currently, the backend fails to install fertiscan-pipeline package. Upon installing requirements we get : 
> Run python -m pip install --upgrade pip
  Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages (24.2)
  Collecting ruff==0.1.0
    Using cached ruff-0.1.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
  Using cached ruff-0.1.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
  Installing collected packages: ruff
  Successfully installed ruff-0.1.0
  Collecting git+https://github.com/ai-cfia/fertiscan-pipeline.git@v0.0.1 (from -r requirements.txt (line 7))
    Cloning https://github.com/ai-cfia/fertiscan-pipeline.git (to revision v0.0.1) to /tmp/pip-req-build-si5h4p1k
    Running command git clone --filter=blob:none --quiet https://github.com/ai-cfia/fertiscan-pipeline.git /tmp/pip-req-build-si5h4p1k
    Resolved https://github.com/ai-cfia/fertiscan-pipeline.git to commit 20fed06c09d89327b8a165bb2791bc5eacfa4d68
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [14 lines of output]
        error: Multiple top-level packages discovered in a flat-layout: ['pipeline', '
        To avoid accidental inclusion of unwanted files or directories,
        setuptools will not proceed with this build.
        If you are trying to create a single distribution with multiple packages
        on purpose, you should not rely on automatic discovery.
        Instead, consider the following options:
        1. set up custom discovery (find directive with include or exclude)
        2. use a src-layout
        3. explicitly set py_modules or packages with a list of names
        To find more information, look for "package discovery" on setuptools docs.
        [end of output]
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

This is because  we have multiple top-level packages (pipeline and test_data) in the same directory without explicitly specifying package discovery

Fix : 

Modify pyproject.toml like this:

```toml
  [tool.setuptools]
  packages = ["pipeline"]
```

**Comment by k-allagbe** [comment]
Closing this as fixed in #56
