### ISSUE TITLE
Improving the performance assessment script

### ISSUE THREAD

**Issue by saratavakoli77** [ai-cfia/fertiscan-pipeline#76]
Current performance assessment works well on exact matching the expected value and the actual value, but there are thing to be fixed on it:

- [ ] When the expected value is null, the accuracy is 100% cause both the actual and expected value are None
- [ ] not checking phone number in different formats: 450-587-5222 and +14505875222 are not different.
- [ ] it should not be case sensitive
- [ ] not using exact match for numbers, 10, 10.0 are not different

**Comment by Endlessflow** [comment]
I assure you those are far from the only things wrong with that script. 😂 
But I'm confused, didn't we all agree we were going to save the trouble of trying to patch that script and fix all those things when we write the metric for DSPy in #62  ?
Or is this suppose to be the issue for the metric implementation 🤔

**Comment by saratavakoli77** [comment]
> I assure you those are far from the only things wrong with that script. 😂 But I'm confused, didn't we all agree we were going to save the trouble of trying to patch that script and fix all those things when we write the metric for DSPy in #62 ? Or is this suppose to be the issue for the metric implementation 🤔

To compare the results of current OCR and the version that is combined with GPT, I have to use an assessment. Right now this is the only way to assess the performance, and I thought to do some improvements to make it more reliable.
